### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [vladimirbacarji/ugc_sprint_2#11]
Привет! Отличная работа и исследование. У меня минимум замечаний:

1. Можно лучше: чтобы не класть [такие](https://github.com/vladimirbacarji/ugc_sprint_2/blob/6d65c7e9f21ea36ad506a2f163edc812f204c8fb/docs/realization.md?plain=1#L86) таблички в репо - можно использовать бейджи, добавляя их в readme: https://github.com/dwyl/repo-badges
2. Можно лучше: для генерации случайных [данных](https://github.com/vladimirbacarji/ugc_sprint_2/blob/6d65c7e9f21ea36ad506a2f163edc812f204c8fb/ugc/benchmark/mongodb/test.py#L46) рекомендую использовать https://faker.readthedocs.io/en/master/. А так же https://factoryboy.readthedocs.io/en/stable/ чтобы генерить целые фейковые объекты
3. Можно лучше: [данные](https://github.com/vladimirbacarji/ugc_sprint_2/blob/main/docker/filebeat/filebeat.yml), которые собирает filebeat у вас складываются в ежедневный индекс. Это здорово, если мы собираем логи nginx, которых очень много. Но если вы собираете логи со множества контейнеров, то пихать их все в один индекс не очень хорошая идея. Искать будет тяжело. Поэтому обычно filebeat настраивают для записи в logstash, который уже может роутить логи в зависимости от приложения. Пример настройки logstash для работы с filebeat: https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html
4. Не очень понял, что вы [тут](https://github.com/vladimirbacarji/ugc_sprint_2/blob/6d65c7e9f21ea36ad506a2f163edc812f204c8fb/ugc/public/app/common/app.py#L34) измеряете...если time два раза вызываете на соседних строчках
5. Вы пропустили в [доке](https://docs.sentry.io/platforms/python/configuration/sampling/#setting-a-uniform-sample-rate) sentry, что [этот](https://github.com/vladimirbacarji/ugc_sprint_2/blob/6d65c7e9f21ea36ad506a2f163edc812f204c8fb/ugc/public/app/common/app.py#L107) параметр нельзя оставлять равным 1. А я рекомендую вообще его не указывать, либо задавать равным нулю, либо перенести опять же в конфиг. Почему? Потому что это не про рейт отправки ошибок. А про транзакции, а транзакции - это аналог средств мониторинга вроде statsd, telegraf and etc. То есть разработчики sentry запилили свою систему сбора метрик, но она откровенно говоря плохо работает под нагрузкой. У меня в компании мы как-то пробовали ее, так вот наша self-hosted sentry упала при 10% транзакций. В общем, будьте аккуратны с этим параметром.
6. С версии python 3.9 для стандартных [коллекций](https://github.com/vladimirbacarji/ugc_sprint_2/blob/6d65c7e9f21ea36ad506a2f163edc812f204c8fb/ugc/public/app/schemas/bookmark.py#L20) больше не нужен модуль typing: [https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections](https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections). Поправьте во всем проекте. Кстати, еще есть классный пакет, который апдейтит ваш код под синтаксис новой версии python: https://github.com/asottile/pyupgrade
7. Для логирования [исключений](https://github.com/vladimirbacarji/ugc_sprint_2/blob/6d65c7e9f21ea36ad506a2f163edc812f204c8fb/ugc/public/app/storage/storage.py#L64) рекомендую делать так (соберете еще и трэйсбэк ошибки):
```
logging.exception("Error add item: ")
```
8. Не уверен, что [это](https://github.com/vladimirbacarji/ugc_sprint_2/blob/6d65c7e9f21ea36ad506a2f163edc812f204c8fb/ugc/public/app/storage/storage.py#L107) хороший подход. Смотрите, этот спринт про данные пользователя. И если вы вместо запрошенной, например, закладки вернете пустоту, то у юзера в интерфейсе не будет закладки, при этом ошибки он тоже никакой не увидит. И побежит в поддержку паниковать, что у него все пропало. В таком случае стоит выбрасывать кастомную ошибку и возвращать 500ый код, например
9. [Так](https://github.com/vladimirbacarji/ugc_sprint_2/blob/6d65c7e9f21ea36ad506a2f163edc812f204c8fb/ugc/public/app/api/v1/bookmark.py#L41) делать не стоит. Лучше обрабатывать только те ошибки, которые можно как-то объяснить юзеры. Например, что он уже добавил такой фильм в закладки. Все остальное не стоит перехватывать. В случае ошибки, это все будет перехвачено хендлерами FastAPI, отправлено в sentry. Да, юзер получит 500ую ошибку, но это и правильно. Ведь у вас случилась ошибка, которую вы не ожидали

**Comment by vladimirbacarji** [comment]
1 - done

**Comment by vladimirbacarji** [comment]
по пункту 3 - это осознанный выбор, у нас ( на текущем месте работы ) в начале так и было сделано, и в итоге мы упелись через 3 месяца в ограничение на кол-во shard в elasticsearch, по итогу мы перевели на схему, все похожее кидается в 1 индекс, а оттуда уже фильтрами достаем необходимое

**Comment by vladimirbacarji** [comment]
по пункту 2 - понял, принял осознал, в будущем попробуем

**Comment by esergeevacom** [comment]
5, 8, 9 - исправлено

по поводу п. 6 у нас [так и было](https://github.com/vladimirbacarji/ugc_sprint_2/commit/f8d90718c5755c12fb365538bf12b9d0536e6a82), только согласно ТЗ от QA нужно было"Сделать проверку работоспособности кода на версиях python 3.7, 3.8 и 3.9."
Поэтому для поддержи совместисмости с младшими версиями python пришлось поменять на old school
